### ISSUE TITLE
Async adding pages to the ViewPager

### ISSUE THREAD

**Issue by mitko9000** [commonsguy/cwac-pager#11]
Let's that we have a fragment that need some time to initialize if I add a new page the whole viewPagger will freeze until the page is added.

Is there a way to add the page async because a tried but I get must execute on the main thread ?

Also if not possible how to escape the freeze moment when loading pages ?

**Comment by commonsguy** [comment]
This is an *issue tracker*. The project `README` has [instructions for where to ask questions](https://github.com/commonsguy/cwac-pager#questions).

> Let's that we have a fragment that need some time to initialize if I add a new page the whole viewPagger will freeze until the page is added.

Your fragment has a performance bug. Fix it. This has nothing to do with this project, or `ViewPager`.
